#!/bin/sh

alias tree='tree -a -I .git'
alias la='ls -la'
alias ll='ls -1'
alias v='nvim'
alias upg='sudo pacman -Suy && yay -Suy'
alias lf='lfcd'
alias zathura='$HOME/.local/bin/zaread'
alias mpv_webcam='mpv av:v417:/dev/video4 --profile=low-latency --untimed'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias song='yt-dlp -x --audio-format mp3 -o "~/media/music/%(channel)s - %(title)s.%(ext)s" --embed-thumbnail --cookies-from-browser firefox'
alias calc='qalc'
alias backup='rsync -avh --info=progress2 --exclude ".config/discord" --exclude ".config/Signal" --exclude ".config/vesktop" media personal school notes .config /mnt/nas'
